# Generated by Django 5.0.6 on 2024-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Like', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=25)),
                ('Img', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
