# Generated by Django 5.0.3 on 2024-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_db', '0004_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
